# Generated by Django 4.1.6 on 2024-03-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formdetails",
            name="file",
            field=models.FileField(upload_to="files/"),
        ),
    ]
