# Generated by Django 5.0.2 on 2024-03-16 12:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_formdetails_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdetails',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='formdetails',
            name='sector',
            field=models.CharField(default='Transportation', max_length=100),
        ),
    ]
