# Generated by Django 5.0.2 on 2024-03-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_formdetails_date_formdetails_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdetails',
            name='status',
            field=models.CharField(default='Pending', max_length=250),
        ),
    ]
