# Generated by Django 5.0.2 on 2024-04-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_alter_formdetails_date_alter_formdetails_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdetails',
            name='file',
            field=models.URLField(max_length=1500),
        ),
    ]
