# Generated by Django 5.0.2 on 2024-04-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_alter_formdetails_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdetails',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
